### ISSUE TITLE
extract properties from multiple arrays

### ISSUE THREAD

**Issue by leelax22** [Rooyca/query-json#5]
Hello, I'm writing to ask you a question because there's something I don't know while using the plug-in.

```
{
  "url": "a.com",
  "shared": [
    {
      "id": "a",
      "password": "aaaa",
      "path": "aaaa.md"
    },
    {
      "id": "b",
      "password": "bbbb",
      "path": "bbbb.md"
    }
  ],
  "stripFrontmatter": true,
  "includeNoteName": true,
  "unshareDeletedFiles": false,
  "autoUpdateShares": false
}
```

When I have the following json data, I would like to query and view only shared.path.

In general, I can query with `shared.path` or `shared[*].path`, `shared.*.path`.

I tried to retrieve the data and query it, and each value is extracted with `shared.0.path` and `shared.1.path`. What should I do to extract it all at once?

I've tried this and that, but I'm asking because it doesn't work.

Thank you for the plug-in. Have a nice day

**Comment by Rooyca** [comment]
Hello @leelax22 , 
Thanks for letting me know. 

I just update the plugin. `shared[*].path` should be working.

**Comment by leelax22** [comment]
thanks for rapid update.

but, after I updated the plugin and restart obsidian, it doesn't work still.
Did I do something wrong?

![Obsidian_YjzV8D0Ujg](https://github.com/user-attachments/assets/c4ee3d7d-8f06-4c17-b1a9-69690094e3e4)

**Comment by Rooyca** [comment]
I believe I forgot something, let me check.

**Comment by Rooyca** [comment]
Hey @leelax22,
I had added the `[*]` only for queries inside the code-block. I'll add it to the inline queries as well.

P.S. I hope the data on the gif is fake :shaking_face:.

**Comment by leelax22** [comment]
For my use, it's enough to work within a code block. Thank you!!😀
